export const environment = {
    production: true,
    configFile: '/api/config',
    contract: {
        registryNumber: '',
        renterName: '',
        sex: 'M',
        language: 'it',
        boatLicense: false,
        boatLicenseDetails: '',
        birthPlace: '',
        birthState: '',
        birthDate: '',
        homeTown: '',
        homeState: '',
        homeAddress: '',
        ssn: '',
        phone: '',
        email: '',
        idType: '',
        idNumber: '',
        idIssuer: '',
        idIssueDate: '',
        startDate: '',
        startTime: '',
        endTime: '',
        startFuel: '',
        fuelCost: 1.8,
        rentPrice: null,
        securityDeposit: 100
    }
};
