module.exports = {
    it: {
        LEASE_CONTRACT: 'Contratto di Locazione',
        DATE: 'Data',
        REGISTRY_NO: 'Nr. Registro',
        LEASEHOLDER_DETAILS: 'Anagrafica Locatore',
        BOAT_DETAILS: 'Dati Natante Locato',
        BOAT_TYPE: 'Natante',
        VIN: 'Matricola',
        ENGINE: 'Motore',
        REG_NO: 'Targa',
        TANK: 'Serbatoio',
        CUSTOMER_DETAILS: 'Anagrafica Locatario/Conduttore',
        CUSTOMER_NAME: 'Locatario',
        BIRTH_PLACE: 'Luogo di nascita',
        BIRTH_DATE: 'Data di nascita',
        HOME_TOWN: 'Citta di residenza',
        HOME_ADDRESS: 'Indirizzo',
        SSN: 'Codice Fiscale',
        BOAT_LICENSE: 'Patente nautica',
        NONE: 'Nessuna',
        PHONE: 'Telefono',
        EMAIL: 'Email',
        ID_TYPE: 'Tipo documento',
        ID_NUMBER: 'Nr. documento',
        ISSUED_BY: 'Rilasciato da',
        ISSUE_DATE: 'Data rilascio',
        LEASE_DETAILS: 'Dettagli locazione',
        START_DATE: 'Data inizio',
        END_DATE: 'Data fine',
        START_TIME: 'Ora inizio',
        END_TIME: 'Ora fine',
        START_FUEL: 'Carburante inizio',
        END_FUEL: 'Carburante fine',
        FUEL_COST: 'Costo carburante',
        FUEL_TOTAL: 'Totale carburante',
        RENT_PRICE: 'Importo locazione',
        SECURITY_DEPOSIT: 'Cauzione',
        DEPOSIT: 'Importo in acconto',
        BALANCE: 'Importo a saldo',
        AGREEMENT: 'Le parti convengono e stipulano il presente contratto di locazione alle condizioni contenute ivi e nei documenti allegati di seguito elencati: [Condizioni di Locazione;][Condizioni Natante in Locazione;][Schema di informazione sull\'attività di locazione;][Informativa sulla privacy dei dati personali.]Tali documenti fanno parte integrante del presente contratto e sono stati letti, compresi ed approvati dalle parti.',
        THE_CUSTOMER: 'Il Locatario/Conduttore',
        THE_LEASEHOLDER: 'Il Locatore',
        BUSINESS_INFO_DESC: 'Schema di informazione sull\'attività di locazione',
        RENTER_DECLARATION: 'Io sottoscritto %s nato a %s (%s) il %s e residente a %s (%s) in %s intendo aderire alla proposta di locazione di un natante da diporto come segue:',
        BOAT_TYPE_DESC: 'Tipo di natante',
        BOAT_BRAND: 'Marca',
        BOAT_MODEL: 'Modello',
        BOAT_CERT: 'Omolog. C.E.',
        BOAT_LENGTH: 'L.F.T.',
        BOAT_PEOPLE: 'Max pers. trasp.',
        BOAT_WEIGHT: 'Kg.',
        BOAT_ENGINES: 'Motori',
        ENGINE_BRAND: 'Marca/Mod.',
        ENGINE_POWER: 'Pot. max appl. (KW)',
        ENGINE_VIN: 'Matricola n.',
        INSURER: 'Assic. R.C.',
        INSURANCE_NO: 'Polizza n.',
        INSURANCE_EXP: 'Scadenza',
        OTHER_CERT: 'Certificato di idoneità al noleggio / Certificato di sicurezza',
        I_STATE: 'Dichiaro',
        STATEMENT: [
            'di aver preso visione e ricevuto copia dell\'Ordinanza n. 11/2015, dell\'Ordinanza di Sicurezza Balneare vigente e dell\'Ordinanza di interdizione dei tratti di costa e degli specchi acquei ricadenti nei Comuni di giurisdizione del Circondario Marittimo di Siracusa, emanate dalla Capitaneria di porto di Siracusa, che disciplinano a livello locale l\'esercizio del diporto nautico per finalità turistico ricreative e, in particolare, per quanto concerne le unità a motore, di essere a conoscenza:', [
                'che lo specchio acqueo di 250 metri dalle spiagge e di 100 metri dalle scogliere, durante la stagione estiva, è riservato esclusivamente alla balneazione e conseguentemente interdetto alle unità a motore, così come interdetti sono gli ulteriori 50 metri da tale limite verso il largo (costituenti la fascia di rispetto e di sicurezza per evitare commistioni tra attività di balneazione e navigazione);',
                'che l\'atterraggio e la partenza delle unità a motore deve avvenire utilizzando i previsti corridoi di uscita alla velocità prescritta (non superiore a 3 nodi);',
                'dei limiti di velocità vigenti nella fascia di mare compresa tra i 300 e i 1000 metri dalla riva (non superiore ai 10 nodi, con scafo in dislocamento);',
                'del divieto di balneazione, di navigazione, e di ogni attività incompatibile con la natura del rischio accertato o esistente, nella fascia di mare come meglio specificata dall\'art. 1 dell\'Ord. 38/2014 e ss. mm. ed ii. (frane e smottamenti);'
            ],
            'di aver ricevuto copia della tabella "B" riportante le dotazioni di sicurezza previste dal D.M. n. 146/2008 del Ministero delle Infrastrutture e dei Trasporti;',
            'di intendere effettuare una navigazione entro 6 miglia dalla costa in relazione alla quale ricevo dal locatore le dotazioni di sicurezza descritte nella sopracitata tabella;',
            '%s;',
            'che in caso di necessità, durante lo svolgimento dell\'attività di locazione, sono disponibili i seguenti numeri di telefonia cellulare: %s;',
            'estremi di un documento d\'identità in corso di validità: %s (%s);',
            'di saper nuotare e vogare.'],
        BOAT_LICENSE_YES: 'di essere in possesso di patente nautica %s',
        BOAT_LICENSE_NO: 'di non essere in possesso di patente nautica',
        BOAT_TERMS: 'allegato 2 - condizioni natante in locazione',
        BOAT_CUSTODY_TERMS: 'condizioni del natante al momento del ritiro',
        BOAT_CUSTODY_TERMS_STRUCTURAL: 'Condizioni strutturali del natante',
        BOAT_CUSTODY_TERMS_CUSHIONS: 'Cuscineria',
        BOAT_CUSTODY_TERMS_EQUIPMENT: 'Strumentazione',
        BOAT_CUSTODY_TERMS_ENGINE: 'Motore',
        BOAT_CUSTODY_TERMS_FACILITIES: 'Dotazioni',
        BOAT_CUSTODY_DECLARATION : 'Sottoscrivendo il presente atto il conduttore dichiara espressamente di confermare le condizioni del natante al momento del ritiro, della cuscineria, della strumentazione, del motore, delle dotazioni e dichiara di aver preso adeguata visione e conoscenza della sopra elencata documentazione.',
        PRIVACY_TITLE: 'Informativa sulla tutela della privacy dei dati personali',
        PRIVACY_HEADER_1: 'Informativa resa ai sensi degli articoli 13-14 del GDPR 2016/679 (General Data Protection Regulation)',
        PRIVACY_HEADER_2: 'Gentile Signore/a, ai sensi dell’art. 13 del Regolamento UE 2016/679 ed in relazione alle informazioni di cui si entrerà in possesso, ai fini della tutela delle persone e altri soggetti in materia di trattamento di dati personali, si informa quanto segue.',
        PRIVACY_CONTENT_TITLE_1: '1. Finalità del Trattamento',
        PRIVACY_CONTENT_TEXT_1: 'I dati da Lei forniti verranno utilizzati allo scopo di fornire il servizio da Lei richiesto, ovvero la Locazione o il noleggio di natanti da diporto.',
        PRIVACY_CONTENT_TITLE_2: '2. Modalità del Trattamento',
        PRIVACY_CONTENT_TEXT_2: 'Le modalità con la quale verranno trattati i dati personali contemplano l’ausilio di mezzi informatici quali tablet, smartphone o PC, e supporti cartacei. I dati saranno conservati, ai soli fini fiscali, in archivi sia cartacei che elettronici.',
        PRIVACY_CONTENT_TITLE_3: '3. Conferimento dei dati',
        PRIVACY_CONTENT_TEXT_3: 'Il conferimento dei dati per le finalità di cui al precedente punto 1 sono obbligatori poiché richiesti dalle Autorità competenti (Guardia Costiera) e l’eventuale rifiuto dell’autorizzazione comporta la mancata locazione del natante da diporto richiesto.',
        PRIVACY_CONTENT_TITLE_4: '4. Comunicazione e diffusione dei dati',
        PRIVACY_CONTENT_TEXT_4: 'I dati forniti potranno essere comunicati, qualora richiesti, alle Autorità di controllo quali la Guardia Costiera, la Capitaneria di Porto, la Guardia di Finanza.',
        PRIVACY_CONTENT_TITLE_5: '5. Titolare del Trattamento',
        PRIVACY_CONTENT_TEXT_5: 'Il titolare del trattamento dei dati personali è %s.',
        PRIVACY_CONTENT_TITLE_6: '6. Diritti dell’interessato',
        PRIVACY_CONTENT_TEXT_6_1: 'In ogni momento, Lei potrà esercitare, ai sensi degli articoli dal 15 al 22 del Regolamento UE n. 2016/679, il diritto di:',
        PRIVACY_CONTENT_TEXT_6_2: [
            'chiedere la conferma dell’esistenza o meno di propri dati personali;',
            'ottenere le indicazioni circa le finalità del trattamento, le categorie dei dati personali, i destinatari o le categorie di destinatari a cui i dati personali sono stati o saranno comunicati e, quando possibile, il periodo di conservazione;',
            'ottenere la rettifica e la cancellazione dei dati;',
            'ottenere la limitazione del trattamento;',
            'ottenere la portabilità dei dati, ossia riceverli da un titolare del trattamento, in un formato strutturato, di uso comune e leggibile da dispositivo automatico, e trasmetterli a un altro titolare del trattamento senza impedimenti;',
            'opporsi al trattamento in qualsiasi momento ed anche nel caso di trattamento per finalità di marketing diretto ad un processo decisionale automatizzato relativo alle persone fisiche, compresa la profilazione.',
            'chiedere al titolare del trattamento l’accesso ai dati personali e la rettifica o la cancellazione degli stessi o la limitazione del trattamento che lo riguardano o di opporsi al loro trattamento, oltre al diritto alla portabilità dei dati;',
            'revocare il consenso in qualsiasi momento senza pregiudicare la liceità del trattamento basata sul consenso prestato prima della revoca;',
            'proporre reclamo a un’autorità di controllo.'
        ],
        PRIVACY_FOOTER_1: 'Può esercitare i Suoi diritti con richiesta scritta inviata a %s, o all\'indirizzo mail %s.',
        PRIVACY_FOOTER_2: 'Io sottoscritto/a dichiaro di aver ricevuto l’informativa che precede.',
        PRIVACY_FOOTER_3: 'Io sottoscritto/a alla luce dell’informativa ricevuta:',
        PRIVACY_AGREE: 'esprime il consenso',
        PRIVACY_DISAGREE: 'non esprime il consenso',
        PRIVACY_AGREEMENT_1: 'al trattamento dei miei dati personali inclusi quelli considerati come categorie particolari di dati.',
        PRIVACY_AGREEMENT_2: 'alla comunicazione dei miei dati personali a enti pubblici e società di natura privata per le finalità indicate nell\'informativa.',
        PRIVACY_AGREEMENT_3: 'al trattamento delle categorie particolari dei miei dati personali così come indicati nell\'informativa che precede.'
    }
};