module.exports = {
    it: {
        PAGE: 'Pagina',
        LEASE_CONTRACT: 'Contratto di Locazione',
        DATE: 'Data',
        REGISTRY_NO: 'Nr. Registro',
        LEASEHOLDER_DETAILS: 'Anagrafica Locatore',
        BOAT_DETAILS: 'Dati Natante Locato',
        BOAT_TYPE: 'Natante',
        VIN: 'Matricola',
        ENGINE: 'Motore',
        REG_NO: 'Targa',
        TANK: 'Serbatoio',
        CUSTOMER_DETAILS: 'Anagrafica Locatario/Conduttore',
        CUSTOMER_NAME: 'Locatario',
        BIRTH_PLACE: 'Luogo di nascita',
        BIRTH_DATE: 'Data di nascita',
        HOME_TOWN: 'Citta di residenza',
        HOME_ADDRESS: 'Indirizzo',
        SSN: 'Codice Fiscale',
        BOAT_LICENSE: 'Patente nautica',
        NONE: 'Nessuna',
        PHONE: 'Telefono',
        EMAIL: 'Email',
        ID_TYPE: 'Tipo documento',
        ID_NUMBER: 'Nr. documento',
        ISSUED_BY: 'Rilasciato da',
        ISSUE_DATE: 'Data rilascio',
        LEASE_DETAILS: 'Dettagli locazione',
        START_DATE: 'Data inizio',
        END_DATE: 'Data fine',
        START_TIME: 'Ora inizio',
        END_TIME: 'Ora fine',
        START_FUEL: 'Carburante inizio',
        END_FUEL: 'Carburante fine',
        FUEL_COST: 'Costo carburante',
        FUEL_TOTAL: 'Totale carburante',
        RENT_PRICE: 'Importo locazione',
        SECURITY_DEPOSIT: 'Cauzione',
        DEPOSIT: 'Importo in acconto',
        BALANCE: 'Importo a saldo',
        AGREEMENT: 'Le parti convengono e stipulano il presente contratto di locazione alle condizioni contenute ivi e nei documenti allegati di seguito elencati: [Condizioni di Locazione;][Condizioni Natante in Locazione;][Schema di informazione sull\'attività di locazione;][Informativa sulla privacy dei dati personali.]Tali documenti fanno parte integrante del presente contratto e sono stati letti, compresi ed approvati dalle parti.',
        THE_CUSTOMER: 'Il Locatario/Conduttore',
        THE_LEASEHOLDER: 'Il Locatore',
        BUSINESS_INFO_DESC: 'Schema di informazione sull\'attività di locazione',
        RENTER_DECLARATION: 'Io sottoscritto %s nato a %s (%s) il %s e residente a %s (%s) in %s intendo aderire alla proposta di locazione di un natante da diporto come segue:',
        BOAT_TYPE_DESC: 'Tipo di natante',
        BOAT_BRAND: 'Marca',
        BOAT_MODEL: 'Modello',
        BOAT_CERT: 'Omolog. C.E.',
        BOAT_LENGTH: 'L.F.T.',
        BOAT_PEOPLE: 'Max pers. trasp.',
        BOAT_WEIGHT: 'Kg.',
        BOAT_ENGINES: 'Motori',
        ENGINE_BRAND: 'Marca/Mod.',
        ENGINE_POWER: 'Pot. max appl. (KW)',
        ENGINE_VIN: 'Matricola n.',
        INSURER: 'Assic. R.C.',
        INSURANCE_NO: 'Polizza n.',
        INSURANCE_EXP: 'Scadenza',
        OTHER_CERT: 'Certificato di idoneità al noleggio / Certificato di sicurezza',
        I_STATE: 'Dichiaro',
        STATEMENT: [
            'di aver preso visione e ricevuto copia dell\'Ordinanza n. 11/2015, dell\'Ordinanza di Sicurezza Balneare vigente e dell\'Ordinanza di interdizione dei tratti di costa e degli specchi acquei ricadenti nei Comuni di giurisdizione del Circondario Marittimo di Siracusa, emanate dalla Capitaneria di porto di Siracusa, che disciplinano a livello locale l\'esercizio del diporto nautico per finalità turistico ricreative e, in particolare, per quanto concerne le unità a motore, di essere a conoscenza:', [
                'che lo specchio acqueo di 250 metri dalle spiagge e di 100 metri dalle scogliere, durante la stagione estiva, è riservato esclusivamente alla balneazione e conseguentemente interdetto alle unità a motore, così come interdetti sono gli ulteriori 50 metri da tale limite verso il largo (costituenti la fascia di rispetto e di sicurezza per evitare commistioni tra attività di balneazione e navigazione);',
                'che l\'atterraggio e la partenza delle unità a motore deve avvenire utilizzando i previsti corridoi di uscita alla velocità prescritta (non superiore a 3 nodi);',
                'dei limiti di velocità vigenti nella fascia di mare compresa tra i 300 e i 1000 metri dalla riva (non superiore ai 10 nodi, con scafo in dislocamento);',
                'del divieto di balneazione, di navigazione, e di ogni attività incompatibile con la natura del rischio accertato o esistente, nella fascia di mare come meglio specificata dall\'art. 1 dell\'Ord. 38/2014 e ss. mm. ed ii. (frane e smottamenti);'
            ],
            'di aver ricevuto copia della tabella "B" riportante le dotazioni di sicurezza previste dal D.M. n. 146/2008 del Ministero delle Infrastrutture e dei Trasporti;',
            'di intendere effettuare una navigazione entro 6 miglia dalla costa in relazione alla quale ricevo dal locatore le dotazioni di sicurezza descritte nella sopracitata tabella;',
            '%s;',
            'che in caso di necessità, durante lo svolgimento dell\'attività di locazione, sono disponibili i seguenti numeri di telefonia cellulare: %s;',
            'estremi di un documento d\'identità in corso di validità: %s (%s);',
            'di saper nuotare e vogare.'],
        BOAT_LICENSE_YES: 'di essere in possesso di patente nautica %s',
        BOAT_LICENSE_NO: 'di non essere in possesso di patente nautica',
        BOAT_TERMS: 'allegato 2 - condizioni natante in locazione',
        BOAT_CUSTODY_TERMS: 'condizioni del natante al momento del ritiro',
        BOAT_CUSTODY_TERMS_STRUCTURAL: 'Condizioni strutturali del natante',
        BOAT_CUSTODY_TERMS_CUSHIONS: 'Cuscineria',
        BOAT_CUSTODY_TERMS_EQUIPMENT: 'Strumentazione',
        BOAT_CUSTODY_TERMS_ENGINE: 'Motore',
        BOAT_CUSTODY_TERMS_FACILITIES: 'Dotazioni',
        BOAT_CUSTODY_DECLARATION : 'Sottoscrivendo il presente atto il conduttore dichiara espressamente di confermare le condizioni del natante al momento del ritiro, della cuscineria, della strumentazione, del motore, delle dotazioni e dichiara di aver preso adeguata visione e conoscenza della sopra elencata documentazione.',
        PRIVACY_TITLE: 'Informativa sulla tutela della privacy dei dati personali',
        PRIVACY_HEADER_1: 'Informativa resa ai sensi degli articoli 13-14 del GDPR 2016/679 (General Data Protection Regulation)',
        PRIVACY_HEADER_2: 'Gentile Signore/a, ai sensi dell’art. 13 del Regolamento UE 2016/679 ed in relazione alle informazioni di cui si entrerà in possesso, ai fini della tutela delle persone e altri soggetti in materia di trattamento di dati personali, si informa quanto segue.',
        PRIVACY_CONTENT_TITLE_1: '1. Finalità del Trattamento',
        PRIVACY_CONTENT_TEXT_1: 'I dati da Lei forniti verranno utilizzati allo scopo di fornire il servizio da Lei richiesto, ovvero la Locazione o il noleggio di natanti da diporto.',
        PRIVACY_CONTENT_TITLE_2: '2. Modalità del Trattamento',
        PRIVACY_CONTENT_TEXT_2: 'Le modalità con la quale verranno trattati i dati personali contemplano l’ausilio di mezzi informatici quali tablet, smartphone o PC, e supporti cartacei. I dati saranno conservati, ai soli fini fiscali, in archivi sia cartacei che elettronici.',
        PRIVACY_CONTENT_TITLE_3: '3. Conferimento dei dati',
        PRIVACY_CONTENT_TEXT_3: 'Il conferimento dei dati per le finalità di cui al precedente punto 1 sono obbligatori poiché richiesti dalle Autorità competenti (Guardia Costiera) e l’eventuale rifiuto dell’autorizzazione comporta la mancata locazione del natante da diporto richiesto.',
        PRIVACY_CONTENT_TITLE_4: '4. Comunicazione e diffusione dei dati',
        PRIVACY_CONTENT_TEXT_4: 'I dati forniti potranno essere comunicati, qualora richiesti, alle Autorità di controllo quali la Guardia Costiera, la Capitaneria di Porto, la Guardia di Finanza.',
        PRIVACY_CONTENT_TITLE_5: '5. Titolare del Trattamento',
        PRIVACY_CONTENT_TEXT_5: 'Il titolare del trattamento dei dati personali è %s.',
        PRIVACY_CONTENT_TITLE_6: '6. Diritti dell’interessato',
        PRIVACY_CONTENT_TEXT_6_1: 'In ogni momento, Lei potrà esercitare, ai sensi degli articoli dal 15 al 22 del Regolamento UE n. 2016/679, il diritto di:',
        PRIVACY_CONTENT_TEXT_6_2: [
            'chiedere la conferma dell’esistenza o meno di propri dati personali;',
            'ottenere le indicazioni circa le finalità del trattamento, le categorie dei dati personali, i destinatari o le categorie di destinatari a cui i dati personali sono stati o saranno comunicati e, quando possibile, il periodo di conservazione;',
            'ottenere la rettifica e la cancellazione dei dati;',
            'ottenere la limitazione del trattamento;',
            'ottenere la portabilità dei dati, ossia riceverli da un titolare del trattamento, in un formato strutturato, di uso comune e leggibile da dispositivo automatico, e trasmetterli a un altro titolare del trattamento senza impedimenti;',
            'opporsi al trattamento in qualsiasi momento ed anche nel caso di trattamento per finalità di marketing diretto ad un processo decisionale automatizzato relativo alle persone fisiche, compresa la profilazione.',
            'chiedere al titolare del trattamento l’accesso ai dati personali e la rettifica o la cancellazione degli stessi o la limitazione del trattamento che lo riguardano o di opporsi al loro trattamento, oltre al diritto alla portabilità dei dati;',
            'revocare il consenso in qualsiasi momento senza pregiudicare la liceità del trattamento basata sul consenso prestato prima della revoca;',
            'proporre reclamo a un’autorità di controllo.'
        ],
        PRIVACY_FOOTER_1: 'Può esercitare i Suoi diritti con richiesta scritta inviata a %s, o all\'indirizzo mail %s.',
        PRIVACY_FOOTER_2: 'Io sottoscritto/a dichiaro di aver ricevuto l’informativa che precede.',
        PRIVACY_FOOTER_3: 'Io sottoscritto/a alla luce dell’informativa ricevuta:',
        PRIVACY_AGREE: 'esprimo il consenso',
        PRIVACY_DISAGREE: 'non esprimo il consenso',
        PRIVACY_AGREEMENT_1: 'al trattamento dei miei dati personali inclusi quelli considerati come categorie particolari di dati.',
        PRIVACY_AGREEMENT_2: 'alla comunicazione dei miei dati personali a enti pubblici e società di natura privata per le finalità indicate nell\'informativa.',
        PRIVACY_AGREEMENT_3: 'al trattamento delle categorie particolari dei miei dati personali così come indicati nell\'informativa che precede.',
        RENTAL_TERMS: 'ALLEGATO 1 - Condizioni Generali Di Locazione',
        RENTAL_TERMS_1_TITLE: 'Art. 1 - Oggetto del contratto',
        RENTAL_TERMS_1_DESC: 'Oggetto del presente contratto è la locazione dell\'unità da diporto (natante) indicata nel contratto. Il locatore si obbliga a far godere al locatario-conduttore l\'unità da diporto di cui dispone, per il dato periodo di tempo e a fronte del pagamento del corrispettivo fissato. L\'unità passa in godimento autonomo del conduttore il quale esercita con essa la navigazione e ne assume la responsabilità ed i rischi.',
        RENTAL_TERMS_2_TITLE: 'Art. 2 - Corrispettivo',
        RENTAL_TERMS_2_DESC_1: 'Il costo del noleggio comprende:',
        RENTAL_TERMS_2_DESC_2: ['La locazione dell\'imbarcazione per ore e giorni pattuiti nel "Contratto di Locazione"', 'L\'Assicurazione RCA'],
        RENTAL_TERMS_2_DESC_3: 'Sono esclusi dal costo della locazione: carburante, pulizia al rientro e quant’altro non espressamente previsto. Il costo accessorio per l\'eventuale lavaggio è fissato in € 10,00 (dieci/00) e verrà applicato qualora il natante risultasse eccessivamente sporco, a insindacabile giudizio del locatario.',
        RENTAL_TERMS_3_TITLE: 'Art. 3 - Assicurazione',
        RENTAL_TERMS_3_DESC: 'E’ quella elencata all\'Art. 2; assicura i danni provocati a terzi entro il massimale ed alle condizioni indicati nella polizza. La polizza assicurativa del natante non copre il furto, intero o parziale, del natante, né l\'incendio, né i danni alle persone trasportate. Non sono coperti dall\'assicurazione gli effetti personali, gli abiti, i bagagli o altri oggetti trasportati dagli occupanti; l\'assicurazione è nulla in caso di guida in stato di ebbrezza, o sotto l\'effetto di stupefacenti o qualora il Locatario avesse fornito false informazioni sulla sua identità o sulla validità della patente ove prevista. Il natante non è assicurato con polizza kasko o altre formule simili, pertanto i danni provocati allo stesso sono interamente addebitati al Locatario secondo la stima effettuata dal proprietario, o da un perito qualora il Locatario contestasse il preventivo formulato. Il Locatario dichiara di conoscere le norme riguardanti l\'assicurazione dei natanti in Italia e le norme del Codice di Navigazione. Egli si impegna a non porre in essere condotte e fatti che possano provocare l\'annullamento o l\'inapplicabilità della protezione assicurativa garantita dalla polizza di cui agli art. 2 e 3, che dichiara di aver letto anche nelle condizioni di prenotazione alle quali aderisce. Per ogni altro dettaglio si rinvia al documento di polizza del natante, di cui il locatario-conduttore dichiara di essere a conoscenza, avendone preso visione sul certificato e contrassegno.',
        RENTAL_TERMS_4_TITLE: 'Art. 4 - Abilitazione alla conduzione dell\'unità',
        RENTAL_TERMS_4_DESC: 'Il locatario-conduttore dichiara di essere fornito di patente nautica o, in mancanza della stessa e compatibilmente con la tipologia di natante prescelta, di essere in grado di guidarlo; a tal fine dichiara di aver ricevuto dal locatore le principali informazioni tecniche relative all\'uso del natante ed ogni ulteriore spiegazione relativa al funzionamento del mezzo nautico affidato nonché il corretto utilizzo dei segnali di soccorso e delle dotazioni di bordo. Qualora necessario, è facoltà del conduttore affidarsi a persona di sua fiducia per la guida del natante, sempre mantenendo in capo a sé la personale responsabilità della navigazione ed ogni relativo e conseguente obbligo; tale scelta è subordinata al preventivo gradimento del locatore che, in mancanza di accettazione, potrà liberamente recedere dal contratto senza alcun preavviso e senza restituire alcun anticipo o corrispettivo.',
        RENTAL_TERMS_5_TITLE: 'Art. 5 - Consegna e riconsegna',
        RENTAL_TERMS_5_DESC: 'La consegna e la restituzione del natante locato avvengono presso il Posteggio Nautico di Guarino Sebastiano e Enzo sito ad Avola in via Sebastiano Morale sn. Il periodo di locazione può avere inizio e termine in qualsiasi giorno della settimana, con date e orari concordati e contrattualizzati. Al di fuori dei suddetti orari e giorni, per la presa e riconsegna verrà addebitata una somma accessoria il cui ammontare viene ridefinito tra il locatore e il Locatario.',
        RENTAL_TERMS_6_TITLE: 'Art 6 - Rischio di trasferimento del natante',
        RENTAL_TERMS_6_DESC: 'Il mezzo si ritira e si riconsegna presso il Posteggio Nautico di Guarino Sebastiano e Enzo sito ad Avola in via Sebastiano Morale sn. Nel caso in cui il natante venisse noleggiato con richiesta di trasferimento dello stesso ad altro porto o approdo, la responsabilità ed i rischi derivanti dal trasferimento saranno a totale carico del locatario-conduttore.',
        RENTAL_TERMS_7_TITLE: 'Art. 7 - Ritardi',
        RENTAL_TERMS_7_DESC_1: 'Qualora, per qualsiasi motivo, il Locatario dovesse ritardare la restituzione del natante, egli sarà tenuto a darne immediata comunicazione telefonica al Locatore che potrà, ove possibile, autorizzare la ritardata consegna indicandone le modalità e le condizioni. In difetto di tale comunicazione il Locatore è autorizzato, decorse ventiquattro ore dall\'ora pattuita per la consegna, a denunciarne il furto alle Autorità competenti. In ogni caso di ritardata consegna del natante non concordata, verrà addebitato al Locatario un importo pari a:',
        RENTAL_TERMS_7_DESC_2: [
            'Da 1 a 15 minuti, nessun supplemento;',
            'Da 15 a 30 minuti, € 15,00 (quindici/00);',
            'Da 30 a 60 minuti, € 30,00 (trenta/00);',
            'Da 1 a 2 ore, € 80,00 (ottanta/00);',
            'Da 2 a 4 ore, € 160,00 (centosessanta/00);',
            'Da 4 a 12 ore, € 250,00 (duecentocinquanta/00);',
            'Oltre le 12 ore di ritardo verrà applicata una tariffa giornaliera di € 400,00 (quattrocento/00).',
        ],
        RENTAL_TERMS_8_TITLE: 'Art. 8 - Riconsegna fuori sede',
        RENTAL_TERMS_8_DESC: 'Qualora il natante non venisse riconsegnato nella località pattuita dal Contratto di Locazione, i costi della presa in consegna del natante, del trasporto marino o terrestre fino alla località concordata e dei giorni eccedenti il periodo di locazione, saranno addebitati al Locatario. Nel caso in cui il natante si dovesse guastare durante il periodo di locazione, il Locatario ha l\'obbligo di avvisare prontamente il Locatore e di attendere la riparazione del natante se possibile in tempi brevi non superiori alle tre ore. Non è consentito in nessun caso lasciare il natante incustodito presso un pontile o altro punto di approdo e rientrare con altri mezzi. In caso contrario le spese di recupero del natante saranno interamente addebitate al Locatario.',
        RENTAL_TERMS_9_TITLE: 'Art. 9 - Condizioni del natante',
        RENTAL_TERMS_9_DESC: 'Il Locatario dichiara di aver ispezionato, verificato e controllato il natante, le dotazioni di bordo e gli accessori e di averne riscontrato le buone condizioni di manutenzione, l\'assenza di vizi palesi, oltre che il funzionamento, così come la rispondenza nell\'inventario Allegato 2 ai documenti di contratto. Il natante deve essere restituito integro, con il lubrificante al livello ed in perfetto stato di funzionamento e di pulizia interna ed esterna. In difetto, i costi di manodopera e materiali per il ripristino alle condizioni richieste saranno addebitate al Locatario.',
        RENTAL_TERMS_10_TITLE: 'Art. 10 - Danni e perdite dotazioni',
        RENTAL_TERMS_10_DESC: 'In caso di danni o perdita di tutta o parte delle dotazioni di bordo, al Locatario sarà addebitato il costo delle riparazioni o il controvalore dei beni in dotazione a valore a nuovo indicato sullo stampato allegato ai documenti di contratto.',
        RENTAL_TERMS_11_TITLE: 'Art. 11 - Carburante',
        RENTAL_TERMS_11_DESC: 'Il quantitativo di carburante presente al momento del ritiro del natante è quello indicato nel Contratto di Locazione, generalmente il pieno, salvo diversa pattuizione indicata in contratto. Al rientro del natante è previsto, per ogni litro di carburante mancante, l\'addebito di €/LT %s',
        RENTAL_TERMS_12_TITLE: 'Art. 12 - Animali a bordo',
        RENTAL_TERMS_12_DESC: 'E\' permesso far salire a bordo del natante animali domestici di piccola taglia. E\' vietato far salire a bordo del natante animali domestici di media e grande taglia; in questo caso, la penale applicata sarà di € 100,00 (cento/00) per pulizia, controllo accurato ed eventuale disinfestazione, salvo ulteriori danni.',
        RENTAL_TERMS_13_TITLE: 'Art. 13 - Guasti meccanici',
        RENTAL_TERMS_13_DESC: 'Le spese relative alla riparazione di guasti meccanici non imputabili al Locatario, e da Questi anticipate al Locatore, saranno rimborsate al rientro su presentazione di ricevuta fiscale accompagnata dalle parti eventualmente sostituite. Il rimborso non avverrà senza che dette parti e ricevute siano esibite al rientro del natante, né se la spesa di riparazione non fosse stata preventivamente comunicata al Locatore.',
        RENTAL_TERMS_14_TITLE: 'Art. 14 - Uso del natante',
        RENTAL_TERMS_14_DESC_1: 'Il natante, durante tutto il periodo di locazione, dovrà essere utilizzato con la massima cura e diligenza; in particolare:',
        RENTAL_TERMS_14_DESC_2: [
            'Non potrà essere utilizzato e condotto in condizioni di sovraccarico e con a bordo un numero di persone superiore a quello autorizzato dall\'omologazione della barca e sul Contratto di Locazione;',
            'Non potrà allontanarsi dalla costa oltre le sei miglia marine;',
            'Non potrà essere condotto al di fuori delle acque nazionali;',
            'Non potrà essere utilizzato da persone in stato di affaticamento, ubriachezza, invalidità anche temporanea e sotto l\'effetto di sostanze stupefacenti;',
            'Non potrà essere utilizzato da persone con età inferiore a 18 anni e/o superiore a 80 anni;',
            'Non potrà essere utilizzato per finalità illecite;',
            'Non potrà essere utilizzato per trainare altri natanti o imbarcazioni;',
            'Non potrà essere utilizzato per gare e competizioni di alcun genere;',
            'Non potrà essere utilizzato a velocità superiori a quelle consentite dalle norme della Capitaneria di Porto e, in particolare, a regime superiore a 5000 RpM.',
            'Non potrà essere utilizzato per scopi commerciali, quali, ad esempio, il trasporto di merci o persone, la sublocazione e la cessione di contratto;',
            'Non potrà essere utilizzato fuori dai limiti di abilitazione dell\'imbarcazione anche in relazione alle dotazioni di sicurezza presenti a bordo o di abilitazione del comandante dell\'unità così come risultanti dalla patente nautica;',
            'Non potrà essere utilizzato per praticare attività pericolose per i terzi trasportati ed i bagnanti;',
            'Non potrà essere utilizzato in condizioni non sicure, come ad esempio navigazione vietata dalle autorità, maltempo o pericolosità del mare; in tali casi si raccomanda di non uscire in mare aperto e di rientrare subito nel porto più vicino o posto sufficientemente sicuro, avvertendo immediatamente il locatore per concordare le modalità di rientro;',
            'Non potrà lasciare incustodita l\'unità da diporto per nessun motivo ed in nessuna circostanza;',
            'Non potrà utilizzare per la pulizia dell\'unità, esterna o interna, alcun detersivo che possa danneggiarne i materiali;',
        ],
        RENTAL_TERMS_14_DESC_3: 'Ogniresponsabilità civile, penale e amministrativa o obbligazione derivante dall\'utilizzo dell\'unità in violazione del contratto o delle norme della navigazione, oltre che della diligenza ordinaria e richiesta dalle circostanze specifiche, sarà a totale carico del Locatario.',
        RENTAL_TERMS_15_TITLE: 'Art. 15 - Responsabilità penale e civile',
        RENTAL_TERMS_15_DESC: 'Il Locatario sarà direttamente responsabile di ogni violazione alle leggi regolanti la Navigazione. In ogni caso, in caso di furto del natante, di tutte o parte delle dotazioni, di incendio o incidente, il Locatario dovrà darne immediatamente comunicazione verbale telefonica al Locatore e entro e non oltre 24 ore tramite mail, raccomandata o fax. Nei casi dei danni provocati a cose di terzi o subiti da terzi, il Locatario dovrà compilare in tutte le sue parti i documenti necessari per attivare le procedure che regolano i sinistri in mare. In ogni altro caso il Locatario è tenuto a richiedere l\'intervento delle Autorità di Polizia Marittima, curare che sui verbali o segnalazioni di incidente siano riportati generalità ed indirizzi delle persone coinvolte, dei testimoni e le generalità/caratteristiche dei natanti o imbarcazioni. Sarà cura del Locatario ottenere copia dei verbali delle Autorità di Polizia. Il Locatario inoltre non potrà accettare responsabilità o transigere liti, non potrà comunque impegnare a riguardo il Locatore; in ogni caso quest\'ultimo non risponderà dei danni occorsi al Locatario e/o alle persone trasportate e non, terzi e non terzi rispetto al Locatario.',
        RENTAL_TERMS_16_TITLE: 'Art. 16 - Danni al natante e da navigazione',
        RENTAL_TERMS_16_DESC_1: 'Il Locatario risarcirà il Locatore di ogni danno subito dal natante, per qualunque evento, connesso e non con l\'uso che derivasse o non da colpa del Locatario. I danni saranno quindi quantificati in base a:',
        RENTAL_TERMS_16_DESC_2: [
            'Preventivi delle Aziende che forniscono le parti di ricambio del natante;',
            'Preventivi delle Aziende che provvedono alla riparazione del natante;',
            'Giorni di fermo del natante, qualora i tempi di riparazione superassero i due giorni costringendo a uno stazionamento forzato, con costo giornaliero pari a quello praticato per il periodo dell\'anno in corso.',
        ],
        RENTAL_TERMS_16_DESC_3: 'Il preventivo di spesa sarà per intero rimborsato dal Locatario entro e non oltre dieci giorni solari dall\'emissione dello stesso. Trascorsi i dieci giorni il Locatario procederà all\'incasso della cauzione, se prevista, provvedendo a rimborsare la differenza in caso di importo inferiore all\'importo del preventivo. Viceversa, in caso di importo superiore alla somma della cauzione, se prevista, il Locatore adirà le vie legali senza preavviso alcuno. Il Locatario, inoltre, autorizza il Locatore a trattenere la cauzione, se prevista, per l\'ipotesi del danno al natante cagionato da terzi e con responsabilità di terzi, fino al momento dell\'eventuale risarcimento da parte dell\'Assicurazione. La cauzione, dedotto quanto non risarcito dall\'Assicurazione ed effettuate le altre deduzioni previste dalle Condizioni Generali di Locazione in quanto applicabili, sarà restituita al Locatario, senza interessi, al risarcimento da parte dell\'assicurazione. Nel caso di violazione delle norme regolanti la navigazione e di quanto disposto dal presente documento, il Locatario sarà responsabile per l\'intero ammontare del danno e della perdita. Oltre al risarcimento danni di cui al presente articolo, in caso di sinistro verificatosi per colpa attribuibile, anche in concorso, al Locatario, verrà applicata allo stesso una penale minima di € 350,00 (trecentocinquanta/00) per ogni sinistro.',
        RENTAL_TERMS_17_TITLE: 'Art. 17 - Addebiti per spese sopravvenute e danni occulti',
        RENTAL_TERMS_17_DESC: 'Il Locatore avrà facoltà di addebitare al Locatario ogni somma eventualmente richiesta dalle competenti Autorità per multe, sanzioni amministrative, non pagati, ecc., relativamente al periodo di locazione. Entro il decimo giorno dalla riconsegna del natante il Locatore avrà altresì la facoltà di esigere dal Locatario le somme dovute per danni occulti e non riscontrati al momento della riconsegna del natante. Il Locatario rimborserà il Locatore di tutte le spese sopravvenute e/o danni occulti riscontrati, su richiesta del Locatore stesso anche in caso di già avvenuta restituzione del deposito cauzionale, se previsto.',
        RENTAL_TERMS_18_TITLE: 'Art. 18 - Danni al locatario ed a terzi',
        RENTAL_TERMS_18_DESC: 'Il Locatore non è responsabile per danni a cose o persone derivanti al Locatario o a terzi in connessione con l\'uso del natante, né per perdite o inconvenienti da guasti meccanici né per ogni altra ragione o fatto, dei quali il Locatario mantiene la piena responsabilità.',
        RENTAL_TERMS_19_TITLE: 'Art. 19 - Impossibilità nell\'uso del natante',
        RENTAL_TERMS_19_DESC: 'Salvi i casi previsti dal successivo articolo 20, nessun rimborso spese, restituzione o riduzione dell\'importo previsto dal Contratto di Locazione sarà dovuto dal Locatore al Locatario per l\'impossibilità, da qualunque causa determinata, di utilizzare il natante durante il periodo di locazione. Nessuna riduzione o rimborso saranno inoltre riconosciuti per rientri anticipati.',
        RENTAL_TERMS_20_TITLE: 'Art. 20 - Condizioni meteo avverse',
        RENTAL_TERMS_20_DESC: 'In caso di condizioni meteo avverse, qualora il Locatario avesse già versato un acconto per la prenotazione del natante, la locazione verrà spostata alla prima data disponibile o rimborsata per intero a scelta del Locatario. Qualora, in caso di condizioni meteo avverse, il Locatario decidesse di anticipare il rientro entro la mezza giornata, verrà rimborsato per un importo pari a quello derivante la differenza tra il prezzo dell\'intera giornata e il prezzo della mezza giornata. Qualora, in caso di condizioni meteo avverse, il Locatario decidesse di anticipare il rientro dopo la mezza giornata, nessun importo verrà rimborsato.',
        RENTAL_TERMS_21_TITLE: 'Art. 21 - Custodia del natante',
        RENTAL_TERMS_21_DESC: 'Il Locatario si impegna durante le soste a lasciare il natante solo ed esclusivamente presso pontili autorizzati e con regolare licenza, nonché custoditi. Il Locatario dichiara di assumersi la piena responsabilità della custodia del natante durante tutto il periodo di locazione.',
        RENTAL_TERMS_22_TITLE: 'Art. 22 - Deposito dell\'autovettura',
        RENTAL_TERMS_22_DESC: 'Qualora il Locatario, durante il periodo di locazione del natante, parcheggiasse la propria autovettura nei pressi del Posteggio Nautico di Guarino Sebastiano e Enzo sito ad Avola in via Sebastiano Morale sn, né lo stesso, né il Locatore avranno obbligo di custodia, pertanto non risponderanno di eventuali furti totali o parziali, incendio e/o altri danni altri sulla autovettura.',
        RENTAL_TERMS_23_TITLE: 'Art. 23 - Foro esclusivo',
        RENTAL_TERMS_23_DESC: 'Per ogni controversia nascente o comunque derivante dal presente contratto sarà territorialmente competente il Foro di Siracusa competente per valore e per materia secondo la legge.',
        RENTAL_TERMS_24_TITLE: 'Art. 24 - Tutela della privacy',
        RENTAL_TERMS_24_DESC: 'Con riferimento alle disposizioni previste dal D. Lgs. 30/06/2003 nr. 196 sulla tutela della privacy, le parti si danno atto reciprocamente che i dati personali, forniti obbligatoriamente per la stipula del presente Contratto di Locazione e Condizioni di Locazione, sono oggetto di trattamento informatico e/o manuale e potranno essere utilizzati esclusivamente per gli adempimenti degli obblighi contrattuali, la gestione amministrativa del rapporto locativo, rapporti con l\'autorità giudiziaria e per adempimenti di legge relativi a norme civilistiche, fiscali e contabili.',
        RENTAL_TERMS_FOOTER: 'Ai sensi degli artt. 1341 e 1342 C.C. il conduttore dichiara espressamente di aver letto, compreso ed approvato gli Art. 3 (Assicurazione), 4 (Abilitazione alla conduzione dell’unità), 5 (Consegna e riconsegna), 6 (Rischio di trasferimento del natante), 7 (Ritardi), 9 (Condizioni del natante), 10 (Danni e perdite dotazioni), 14 (Uso del natante), 15 (Responsabilità penale e civile), 16 (Danni al natante e da navigazione), 17 (Addebiti per spese sopravvenute e danni occulti), 18 (Danni al locatario ed a terzi), 19 (Impossibilità nell\'uso del natante), 20 (Condizioni meteo avverse), 23 (Foro esclusivo), e per accettazione le sottoscrive.'
    },
    en: {
        PAGE: 'Page',
        LEASE_CONTRACT: 'Lease Contract',
        DATE: 'Date',
        REGISTRY_NO: 'Register #',
        LEASEHOLDER_DETAILS: 'Leaseholder details',
        BOAT_DETAILS: 'Boat details',
        BOAT_TYPE: 'Boat type',
        VIN: 'VIN',
        ENGINE: 'Engine',
        REG_NO: 'Reg. no.',
        TANK: 'Tank',
        CUSTOMER_DETAILS: 'Customer details',
        CUSTOMER_NAME: 'Customer name',
        BIRTH_PLACE: 'Birth place',
        BIRTH_DATE: 'Birth date',
        HOME_TOWN: 'Home town',
        HOME_ADDRESS: 'Home address',
        SSN: 'S.S.N.',
        BOAT_LICENSE: 'Boat license',
        NONE: 'None',
        PHONE: 'Phone',
        EMAIL: 'Email',
        ID_TYPE: 'ID Type',
        ID_NUMBER: 'ID Number',
        ISSUED_BY: 'Issued by',
        ISSUE_DATE: 'Issued on',
        LEASE_DETAILS: 'Lease details',
        START_DATE: 'Start date',
        END_DATE: 'End date',
        START_TIME: 'Start time',
        END_TIME: 'End time',
        START_FUEL: 'Start fuel',
        END_FUEL: 'End fuel',
        FUEL_COST: 'Fuel cost',
        FUEL_TOTAL: 'Total fuel',
        RENT_PRICE: 'Rent price',
        SECURITY_DEPOSIT: 'Security deposit',
        DEPOSIT: 'Deposit',
        BALANCE: 'Balance',
        AGREEMENT: 'The customer and the leaseholder both undersign the present lease contract and agree to the terms and conditions in the following sections: [Rental terms and conditions;][Boat conditions terms;][Business informations and description;][Privacy Policy.]These documents are fully part of the contract and are read approved and signed as a true record.',
        THE_CUSTOMER: 'The Customer',
        THE_LEASEHOLDER: 'The Leaseholder',
        BUSINESS_INFO_DESC: 'Business informations and description',
        RENTER_DECLARATION: 'I, the undersigned, %s born in %s (%s) on %s with an address in %s (%s), %s I hereby accept the lease contract of a recreational craft with the following description:',
        BOAT_TYPE_DESC: 'Boat type',
        BOAT_BRAND: 'Brand',
        BOAT_MODEL: 'Model',
        BOAT_CERT: 'E.C. Approval',
        BOAT_LENGTH: 'Overall lenght',
        BOAT_PEOPLE: 'Allowed people',
        BOAT_WEIGHT: 'Kg.',
        BOAT_ENGINES: 'Engines',
        ENGINE_BRAND: 'Brand/Model',
        ENGINE_POWER: 'Power (KW)',
        ENGINE_VIN: 'VIN',
        INSURER: 'Insurance Policy',
        INSURANCE_NO: 'Policy n.',
        INSURANCE_EXP: 'Expiration',
        OTHER_CERT: 'Certificato di idoneità al noleggio / Certificato di sicurezza',
        I_STATE: 'Dichiaro',
        STATEMENT: [
            'di aver preso visione e ricevuto copia dell\'Ordinanza n. 11/2015, dell\'Ordinanza di Sicurezza Balneare vigente e dell\'Ordinanza di interdizione dei tratti di costa e degli specchi acquei ricadenti nei Comuni di giurisdizione del Circondario Marittimo di Siracusa, emanate dalla Capitaneria di porto di Siracusa, che disciplinano a livello locale l\'esercizio del diporto nautico per finalità turistico ricreative e, in particolare, per quanto concerne le unità a motore, di essere a conoscenza:', [
                'che lo specchio acqueo di 250 metri dalle spiagge e di 100 metri dalle scogliere, durante la stagione estiva, è riservato esclusivamente alla balneazione e conseguentemente interdetto alle unità a motore, così come interdetti sono gli ulteriori 50 metri da tale limite verso il largo (costituenti la fascia di rispetto e di sicurezza per evitare commistioni tra attività di balneazione e navigazione);',
                'che l\'atterraggio e la partenza delle unità a motore deve avvenire utilizzando i previsti corridoi di uscita alla velocità prescritta (non superiore a 3 nodi);',
                'dei limiti di velocità vigenti nella fascia di mare compresa tra i 300 e i 1000 metri dalla riva (non superiore ai 10 nodi, con scafo in dislocamento);',
                'del divieto di balneazione, di navigazione, e di ogni attività incompatibile con la natura del rischio accertato o esistente, nella fascia di mare come meglio specificata dall\'art. 1 dell\'Ord. 38/2014 e ss. mm. ed ii. (frane e smottamenti);'
            ],
            'di aver ricevuto copia della tabella "B" riportante le dotazioni di sicurezza previste dal D.M. n. 146/2008 del Ministero delle Infrastrutture e dei Trasporti;',
            'di intendere effettuare una navigazione entro 6 miglia dalla costa in relazione alla quale ricevo dal locatore le dotazioni di sicurezza descritte nella sopracitata tabella;',
            '%s;',
            'che in caso di necessità, durante lo svolgimento dell\'attività di locazione, sono disponibili i seguenti numeri di telefonia cellulare: %s;',
            'estremi di un documento d\'identità in corso di validità: %s (%s);',
            'di saper nuotare e vogare.'],
        BOAT_LICENSE_YES: 'di essere in possesso di patente nautica %s',
        BOAT_LICENSE_NO: 'di non essere in possesso di patente nautica',
        BOAT_TERMS: 'allegato 2 - condizioni natante in locazione',
        BOAT_CUSTODY_TERMS: 'condizioni del natante al momento del ritiro',
        BOAT_CUSTODY_TERMS_STRUCTURAL: 'Condizioni strutturali del natante',
        BOAT_CUSTODY_TERMS_CUSHIONS: 'Cuscineria',
        BOAT_CUSTODY_TERMS_EQUIPMENT: 'Strumentazione',
        BOAT_CUSTODY_TERMS_ENGINE: 'Motore',
        BOAT_CUSTODY_TERMS_FACILITIES: 'Dotazioni',
        BOAT_CUSTODY_DECLARATION : 'Sottoscrivendo il presente atto il conduttore dichiara espressamente di confermare le condizioni del natante al momento del ritiro, della cuscineria, della strumentazione, del motore, delle dotazioni e dichiara di aver preso adeguata visione e conoscenza della sopra elencata documentazione.',
        PRIVACY_TITLE: 'Informativa sulla tutela della privacy dei dati personali',
        PRIVACY_HEADER_1: 'Informativa resa ai sensi degli articoli 13-14 del GDPR 2016/679 (General Data Protection Regulation)',
        PRIVACY_HEADER_2: 'Gentile Signore/a, ai sensi dell’art. 13 del Regolamento UE 2016/679 ed in relazione alle informazioni di cui si entrerà in possesso, ai fini della tutela delle persone e altri soggetti in materia di trattamento di dati personali, si informa quanto segue.',
        PRIVACY_CONTENT_TITLE_1: '1. Finalità del Trattamento',
        PRIVACY_CONTENT_TEXT_1: 'I dati da Lei forniti verranno utilizzati allo scopo di fornire il servizio da Lei richiesto, ovvero la Locazione o il noleggio di natanti da diporto.',
        PRIVACY_CONTENT_TITLE_2: '2. Modalità del Trattamento',
        PRIVACY_CONTENT_TEXT_2: 'Le modalità con la quale verranno trattati i dati personali contemplano l’ausilio di mezzi informatici quali tablet, smartphone o PC, e supporti cartacei. I dati saranno conservati, ai soli fini fiscali, in archivi sia cartacei che elettronici.',
        PRIVACY_CONTENT_TITLE_3: '3. Conferimento dei dati',
        PRIVACY_CONTENT_TEXT_3: 'Il conferimento dei dati per le finalità di cui al precedente punto 1 sono obbligatori poiché richiesti dalle Autorità competenti (Guardia Costiera) e l’eventuale rifiuto dell’autorizzazione comporta la mancata locazione del natante da diporto richiesto.',
        PRIVACY_CONTENT_TITLE_4: '4. Comunicazione e diffusione dei dati',
        PRIVACY_CONTENT_TEXT_4: 'I dati forniti potranno essere comunicati, qualora richiesti, alle Autorità di controllo quali la Guardia Costiera, la Capitaneria di Porto, la Guardia di Finanza.',
        PRIVACY_CONTENT_TITLE_5: '5. Titolare del Trattamento',
        PRIVACY_CONTENT_TEXT_5: 'Il titolare del trattamento dei dati personali è %s.',
        PRIVACY_CONTENT_TITLE_6: '6. Diritti dell’interessato',
        PRIVACY_CONTENT_TEXT_6_1: 'In ogni momento, Lei potrà esercitare, ai sensi degli articoli dal 15 al 22 del Regolamento UE n. 2016/679, il diritto di:',
        PRIVACY_CONTENT_TEXT_6_2: [
            'chiedere la conferma dell’esistenza o meno di propri dati personali;',
            'ottenere le indicazioni circa le finalità del trattamento, le categorie dei dati personali, i destinatari o le categorie di destinatari a cui i dati personali sono stati o saranno comunicati e, quando possibile, il periodo di conservazione;',
            'ottenere la rettifica e la cancellazione dei dati;',
            'ottenere la limitazione del trattamento;',
            'ottenere la portabilità dei dati, ossia riceverli da un titolare del trattamento, in un formato strutturato, di uso comune e leggibile da dispositivo automatico, e trasmetterli a un altro titolare del trattamento senza impedimenti;',
            'opporsi al trattamento in qualsiasi momento ed anche nel caso di trattamento per finalità di marketing diretto ad un processo decisionale automatizzato relativo alle persone fisiche, compresa la profilazione.',
            'chiedere al titolare del trattamento l’accesso ai dati personali e la rettifica o la cancellazione degli stessi o la limitazione del trattamento che lo riguardano o di opporsi al loro trattamento, oltre al diritto alla portabilità dei dati;',
            'revocare il consenso in qualsiasi momento senza pregiudicare la liceità del trattamento basata sul consenso prestato prima della revoca;',
            'proporre reclamo a un’autorità di controllo.'
        ],
        PRIVACY_FOOTER_1: 'Può esercitare i Suoi diritti con richiesta scritta inviata a %s, o all\'indirizzo mail %s.',
        PRIVACY_FOOTER_2: 'Io sottoscritto/a dichiaro di aver ricevuto l’informativa che precede.',
        PRIVACY_FOOTER_3: 'Io sottoscritto/a alla luce dell’informativa ricevuta:',
        PRIVACY_AGREE: 'esprimo il consenso',
        PRIVACY_DISAGREE: 'non esprimo il consenso',
        PRIVACY_AGREEMENT_1: 'al trattamento dei miei dati personali inclusi quelli considerati come categorie particolari di dati.',
        PRIVACY_AGREEMENT_2: 'alla comunicazione dei miei dati personali a enti pubblici e società di natura privata per le finalità indicate nell\'informativa.',
        PRIVACY_AGREEMENT_3: 'al trattamento delle categorie particolari dei miei dati personali così come indicati nell\'informativa che precede.',
        RENTAL_TERMS: 'ALLEGATO 1 - Condizioni Generali Di Locazione',
        RENTAL_TERMS_1_TITLE: 'Art. 1 - Oggetto del contratto',
        RENTAL_TERMS_1_DESC: 'Oggetto del presente contratto è la locazione dell\'unità da diporto (natante) indicata nel contratto. Il locatore si obbliga a far godere al locatario-conduttore l\'unità da diporto di cui dispone, per il dato periodo di tempo e a fronte del pagamento del corrispettivo fissato. L\'unità passa in godimento autonomo del conduttore il quale esercita con essa la navigazione e ne assume la responsabilità ed i rischi.',
        RENTAL_TERMS_2_TITLE: 'Art. 2 - Corrispettivo',
        RENTAL_TERMS_2_DESC_1: 'Il costo del noleggio comprende:',
        RENTAL_TERMS_2_DESC_2: ['La locazione dell\'imbarcazione per ore e giorni pattuiti nel "Contratto di Locazione"', 'L\'Assicurazione RCA'],
        RENTAL_TERMS_2_DESC_3: 'Sono esclusi dal costo della locazione: carburante, pulizia al rientro e quant’altro non espressamente previsto. Il costo accessorio per l\'eventuale lavaggio è fissato in € 10,00 (dieci/00) e verrà applicato qualora il natante risultasse eccessivamente sporco, a insindacabile giudizio del locatario.',
        RENTAL_TERMS_3_TITLE: 'Art. 3 - Assicurazione',
        RENTAL_TERMS_3_DESC: 'E’ quella elencata all\'Art. 2; assicura i danni provocati a terzi entro il massimale ed alle condizioni indicati nella polizza. La polizza assicurativa del natante non copre il furto, intero o parziale, del natante, né l\'incendio, né i danni alle persone trasportate. Non sono coperti dall\'assicurazione gli effetti personali, gli abiti, i bagagli o altri oggetti trasportati dagli occupanti; l\'assicurazione è nulla in caso di guida in stato di ebbrezza, o sotto l\'effetto di stupefacenti o qualora il Locatario avesse fornito false informazioni sulla sua identità o sulla validità della patente ove prevista. Il natante non è assicurato con polizza kasko o altre formule simili, pertanto i danni provocati allo stesso sono interamente addebitati al Locatario secondo la stima effettuata dal proprietario, o da un perito qualora il Locatario contestasse il preventivo formulato. Il Locatario dichiara di conoscere le norme riguardanti l\'assicurazione dei natanti in Italia e le norme del Codice di Navigazione. Egli si impegna a non porre in essere condotte e fatti che possano provocare l\'annullamento o l\'inapplicabilità della protezione assicurativa garantita dalla polizza di cui agli art. 2 e 3, che dichiara di aver letto anche nelle condizioni di prenotazione alle quali aderisce. Per ogni altro dettaglio si rinvia al documento di polizza del natante, di cui il locatario-conduttore dichiara di essere a conoscenza, avendone preso visione sul certificato e contrassegno.',
        RENTAL_TERMS_4_TITLE: 'Art. 4 - Abilitazione alla conduzione dell\'unità',
        RENTAL_TERMS_4_DESC: 'Il locatario-conduttore dichiara di essere fornito di patente nautica o, in mancanza della stessa e compatibilmente con la tipologia di natante prescelta, di essere in grado di guidarlo; a tal fine dichiara di aver ricevuto dal locatore le principali informazioni tecniche relative all\'uso del natante ed ogni ulteriore spiegazione relativa al funzionamento del mezzo nautico affidato nonché il corretto utilizzo dei segnali di soccorso e delle dotazioni di bordo. Qualora necessario, è facoltà del conduttore affidarsi a persona di sua fiducia per la guida del natante, sempre mantenendo in capo a sé la personale responsabilità della navigazione ed ogni relativo e conseguente obbligo; tale scelta è subordinata al preventivo gradimento del locatore che, in mancanza di accettazione, potrà liberamente recedere dal contratto senza alcun preavviso e senza restituire alcun anticipo o corrispettivo.',
        RENTAL_TERMS_5_TITLE: 'Art. 5 - Consegna e riconsegna',
        RENTAL_TERMS_5_DESC: 'La consegna e la restituzione del natante locato avvengono presso il Posteggio Nautico di Guarino Sebastiano e Enzo sito ad Avola in via Sebastiano Morale sn. Il periodo di locazione può avere inizio e termine in qualsiasi giorno della settimana, con date e orari concordati e contrattualizzati. Al di fuori dei suddetti orari e giorni, per la presa e riconsegna verrà addebitata una somma accessoria il cui ammontare viene ridefinito tra il locatore e il Locatario.',
        RENTAL_TERMS_6_TITLE: 'Art 6 - Rischio di trasferimento del natante',
        RENTAL_TERMS_6_DESC: 'Il mezzo si ritira e si riconsegna presso il Posteggio Nautico di Guarino Sebastiano e Enzo sito ad Avola in via Sebastiano Morale sn. Nel caso in cui il natante venisse noleggiato con richiesta di trasferimento dello stesso ad altro porto o approdo, la responsabilità ed i rischi derivanti dal trasferimento saranno a totale carico del locatario-conduttore.',
        RENTAL_TERMS_7_TITLE: 'Art. 7 - Ritardi',
        RENTAL_TERMS_7_DESC_1: 'Qualora, per qualsiasi motivo, il Locatario dovesse ritardare la restituzione del natante, egli sarà tenuto a darne immediata comunicazione telefonica al Locatore che potrà, ove possibile, autorizzare la ritardata consegna indicandone le modalità e le condizioni. In difetto di tale comunicazione il Locatore è autorizzato, decorse ventiquattro ore dall\'ora pattuita per la consegna, a denunciarne il furto alle Autorità competenti. In ogni caso di ritardata consegna del natante non concordata, verrà addebitato al Locatario un importo pari a:',
        RENTAL_TERMS_7_DESC_2: [
            'Da 1 a 15 minuti, nessun supplemento;',
            'Da 15 a 30 minuti, € 15,00 (quindici/00);',
            'Da 30 a 60 minuti, € 30,00 (trenta/00);',
            'Da 1 a 2 ore, € 80,00 (ottanta/00);',
            'Da 2 a 4 ore, € 160,00 (centosessanta/00);',
            'Da 4 a 12 ore, € 250,00 (duecentocinquanta/00);',
            'Oltre le 12 ore di ritardo verrà applicata una tariffa giornaliera di € 400,00 (quattrocento/00).',
        ],
        RENTAL_TERMS_8_TITLE: 'Art. 8 - Riconsegna fuori sede',
        RENTAL_TERMS_8_DESC: 'Qualora il natante non venisse riconsegnato nella località pattuita dal Contratto di Locazione, i costi della presa in consegna del natante, del trasporto marino o terrestre fino alla località concordata e dei giorni eccedenti il periodo di locazione, saranno addebitati al Locatario. Nel caso in cui il natante si dovesse guastare durante il periodo di locazione, il Locatario ha l\'obbligo di avvisare prontamente il Locatore e di attendere la riparazione del natante se possibile in tempi brevi non superiori alle tre ore. Non è consentito in nessun caso lasciare il natante incustodito presso un pontile o altro punto di approdo e rientrare con altri mezzi. In caso contrario le spese di recupero del natante saranno interamente addebitate al Locatario.',
        RENTAL_TERMS_9_TITLE: 'Art. 9 - Condizioni del natante',
        RENTAL_TERMS_9_DESC: 'Il Locatario dichiara di aver ispezionato, verificato e controllato il natante, le dotazioni di bordo e gli accessori e di averne riscontrato le buone condizioni di manutenzione, l\'assenza di vizi palesi, oltre che il funzionamento, così come la rispondenza nell\'inventario Allegato 2 ai documenti di contratto. Il natante deve essere restituito integro, con il lubrificante al livello ed in perfetto stato di funzionamento e di pulizia interna ed esterna. In difetto, i costi di manodopera e materiali per il ripristino alle condizioni richieste saranno addebitate al Locatario.',
        RENTAL_TERMS_10_TITLE: 'Art. 10 - Danni e perdite dotazioni',
        RENTAL_TERMS_10_DESC: 'In caso di danni o perdita di tutta o parte delle dotazioni di bordo, al Locatario sarà addebitato il costo delle riparazioni o il controvalore dei beni in dotazione a valore a nuovo indicato sullo stampato allegato ai documenti di contratto.',
        RENTAL_TERMS_11_TITLE: 'Art. 11 - Carburante',
        RENTAL_TERMS_11_DESC: 'Il quantitativo di carburante presente al momento del ritiro del natante è quello indicato nel Contratto di Locazione, generalmente il pieno, salvo diversa pattuizione indicata in contratto. Al rientro del natante è previsto, per ogni litro di carburante mancante, l\'addebito di €/LT %s',
        RENTAL_TERMS_12_TITLE: 'Art. 12 - Animali a bordo',
        RENTAL_TERMS_12_DESC: 'E\' permesso far salire a bordo del natante animali domestici di piccola taglia. E\' vietato far salire a bordo del natante animali domestici di media e grande taglia; in questo caso, la penale applicata sarà di € 100,00 (cento/00) per pulizia, controllo accurato ed eventuale disinfestazione, salvo ulteriori danni.',
        RENTAL_TERMS_13_TITLE: 'Art. 13 - Guasti meccanici',
        RENTAL_TERMS_13_DESC: 'Le spese relative alla riparazione di guasti meccanici non imputabili al Locatario, e da Questi anticipate al Locatore, saranno rimborsate al rientro su presentazione di ricevuta fiscale accompagnata dalle parti eventualmente sostituite. Il rimborso non avverrà senza che dette parti e ricevute siano esibite al rientro del natante, né se la spesa di riparazione non fosse stata preventivamente comunicata al Locatore.',
        RENTAL_TERMS_14_TITLE: 'Art. 14 - Uso del natante',
        RENTAL_TERMS_14_DESC_1: 'Il natante, durante tutto il periodo di locazione, dovrà essere utilizzato con la massima cura e diligenza; in particolare:',
        RENTAL_TERMS_14_DESC_2: [
            'Non potrà essere utilizzato e condotto in condizioni di sovraccarico e con a bordo un numero di persone superiore a quello autorizzato dall\'omologazione della barca e sul Contratto di Locazione;',
            'Non potrà allontanarsi dalla costa oltre le sei miglia marine;',
            'Non potrà essere condotto al di fuori delle acque nazionali;',
            'Non potrà essere utilizzato da persone in stato di affaticamento, ubriachezza, invalidità anche temporanea e sotto l\'effetto di sostanze stupefacenti;',
            'Non potrà essere utilizzato da persone con età inferiore a 18 anni e/o superiore a 80 anni;',
            'Non potrà essere utilizzato per finalità illecite;',
            'Non potrà essere utilizzato per trainare altri natanti o imbarcazioni;',
            'Non potrà essere utilizzato per gare e competizioni di alcun genere;',
            'Non potrà essere utilizzato a velocità superiori a quelle consentite dalle norme della Capitaneria di Porto e, in particolare, a regime superiore a 5000 RpM.',
            'Non potrà essere utilizzato per scopi commerciali, quali, ad esempio, il trasporto di merci o persone, la sublocazione e la cessione di contratto;',
            'Non potrà essere utilizzato fuori dai limiti di abilitazione dell\'imbarcazione anche in relazione alle dotazioni di sicurezza presenti a bordo o di abilitazione del comandante dell\'unità così come risultanti dalla patente nautica;',
            'Non potrà essere utilizzato per praticare attività pericolose per i terzi trasportati ed i bagnanti;',
            'Non potrà essere utilizzato in condizioni non sicure, come ad esempio navigazione vietata dalle autorità, maltempo o pericolosità del mare; in tali casi si raccomanda di non uscire in mare aperto e di rientrare subito nel porto più vicino o posto sufficientemente sicuro, avvertendo immediatamente il locatore per concordare le modalità di rientro;',
            'Non potrà lasciare incustodita l\'unità da diporto per nessun motivo ed in nessuna circostanza;',
            'Non potrà utilizzare per la pulizia dell\'unità, esterna o interna, alcun detersivo che possa danneggiarne i materiali;',
        ],
        RENTAL_TERMS_14_DESC_3: 'Ogniresponsabilità civile, penale e amministrativa o obbligazione derivante dall\'utilizzo dell\'unità in violazione del contratto o delle norme della navigazione, oltre che della diligenza ordinaria e richiesta dalle circostanze specifiche, sarà a totale carico del Locatario.',
        RENTAL_TERMS_15_TITLE: 'Art. 15 - Responsabilità penale e civile',
        RENTAL_TERMS_15_DESC: 'Il Locatario sarà direttamente responsabile di ogni violazione alle leggi regolanti la Navigazione. In ogni caso, in caso di furto del natante, di tutte o parte delle dotazioni, di incendio o incidente, il Locatario dovrà darne immediatamente comunicazione verbale telefonica al Locatore e entro e non oltre 24 ore tramite mail, raccomandata o fax. Nei casi dei danni provocati a cose di terzi o subiti da terzi, il Locatario dovrà compilare in tutte le sue parti i documenti necessari per attivare le procedure che regolano i sinistri in mare. In ogni altro caso il Locatario è tenuto a richiedere l\'intervento delle Autorità di Polizia Marittima, curare che sui verbali o segnalazioni di incidente siano riportati generalità ed indirizzi delle persone coinvolte, dei testimoni e le generalità/caratteristiche dei natanti o imbarcazioni. Sarà cura del Locatario ottenere copia dei verbali delle Autorità di Polizia. Il Locatario inoltre non potrà accettare responsabilità o transigere liti, non potrà comunque impegnare a riguardo il Locatore; in ogni caso quest\'ultimo non risponderà dei danni occorsi al Locatario e/o alle persone trasportate e non, terzi e non terzi rispetto al Locatario.',
        RENTAL_TERMS_16_TITLE: 'Art. 16 - Danni al natante e da navigazione',
        RENTAL_TERMS_16_DESC_1: 'Il Locatario risarcirà il Locatore di ogni danno subito dal natante, per qualunque evento, connesso e non con l\'uso che derivasse o non da colpa del Locatario. I danni saranno quindi quantificati in base a:',
        RENTAL_TERMS_16_DESC_2: [
            'Preventivi delle Aziende che forniscono le parti di ricambio del natante;',
            'Preventivi delle Aziende che provvedono alla riparazione del natante;',
            'Giorni di fermo del natante, qualora i tempi di riparazione superassero i due giorni costringendo a uno stazionamento forzato, con costo giornaliero pari a quello praticato per il periodo dell\'anno in corso.',
        ],
        RENTAL_TERMS_16_DESC_3: 'Il preventivo di spesa sarà per intero rimborsato dal Locatario entro e non oltre dieci giorni solari dall\'emissione dello stesso. Trascorsi i dieci giorni il Locatario procederà all\'incasso della cauzione, se prevista, provvedendo a rimborsare la differenza in caso di importo inferiore all\'importo del preventivo. Viceversa, in caso di importo superiore alla somma della cauzione, se prevista, il Locatore adirà le vie legali senza preavviso alcuno. Il Locatario, inoltre, autorizza il Locatore a trattenere la cauzione, se prevista, per l\'ipotesi del danno al natante cagionato da terzi e con responsabilità di terzi, fino al momento dell\'eventuale risarcimento da parte dell\'Assicurazione. La cauzione, dedotto quanto non risarcito dall\'Assicurazione ed effettuate le altre deduzioni previste dalle Condizioni Generali di Locazione in quanto applicabili, sarà restituita al Locatario, senza interessi, al risarcimento da parte dell\'assicurazione. Nel caso di violazione delle norme regolanti la navigazione e di quanto disposto dal presente documento, il Locatario sarà responsabile per l\'intero ammontare del danno e della perdita. Oltre al risarcimento danni di cui al presente articolo, in caso di sinistro verificatosi per colpa attribuibile, anche in concorso, al Locatario, verrà applicata allo stesso una penale minima di € 350,00 (trecentocinquanta/00) per ogni sinistro.',
        RENTAL_TERMS_17_TITLE: 'Art. 17 - Addebiti per spese sopravvenute e danni occulti',
        RENTAL_TERMS_17_DESC: 'Il Locatore avrà facoltà di addebitare al Locatario ogni somma eventualmente richiesta dalle competenti Autorità per multe, sanzioni amministrative, non pagati, ecc., relativamente al periodo di locazione. Entro il decimo giorno dalla riconsegna del natante il Locatore avrà altresì la facoltà di esigere dal Locatario le somme dovute per danni occulti e non riscontrati al momento della riconsegna del natante. Il Locatario rimborserà il Locatore di tutte le spese sopravvenute e/o danni occulti riscontrati, su richiesta del Locatore stesso anche in caso di già avvenuta restituzione del deposito cauzionale, se previsto.',
        RENTAL_TERMS_18_TITLE: 'Art. 18 - Danni al locatario ed a terzi',
        RENTAL_TERMS_18_DESC: 'Il Locatore non è responsabile per danni a cose o persone derivanti al Locatario o a terzi in connessione con l\'uso del natante, né per perdite o inconvenienti da guasti meccanici né per ogni altra ragione o fatto, dei quali il Locatario mantiene la piena responsabilità.',
        RENTAL_TERMS_19_TITLE: 'Art. 19 - Impossibilità nell\'uso del natante',
        RENTAL_TERMS_19_DESC: 'Salvi i casi previsti dal successivo articolo 20, nessun rimborso spese, restituzione o riduzione dell\'importo previsto dal Contratto di Locazione sarà dovuto dal Locatore al Locatario per l\'impossibilità, da qualunque causa determinata, di utilizzare il natante durante il periodo di locazione. Nessuna riduzione o rimborso saranno inoltre riconosciuti per rientri anticipati.',
        RENTAL_TERMS_20_TITLE: 'Art. 20 - Condizioni meteo avverse',
        RENTAL_TERMS_20_DESC: 'In caso di condizioni meteo avverse, qualora il Locatario avesse già versato un acconto per la prenotazione del natante, la locazione verrà spostata alla prima data disponibile o rimborsata per intero a scelta del Locatario. Qualora, in caso di condizioni meteo avverse, il Locatario decidesse di anticipare il rientro entro la mezza giornata, verrà rimborsato per un importo pari a quello derivante la differenza tra il prezzo dell\'intera giornata e il prezzo della mezza giornata. Qualora, in caso di condizioni meteo avverse, il Locatario decidesse di anticipare il rientro dopo la mezza giornata, nessun importo verrà rimborsato.',
        RENTAL_TERMS_21_TITLE: 'Art. 21 - Custodia del natante',
        RENTAL_TERMS_21_DESC: 'Il Locatario si impegna durante le soste a lasciare il natante solo ed esclusivamente presso pontili autorizzati e con regolare licenza, nonché custoditi. Il Locatario dichiara di assumersi la piena responsabilità della custodia del natante durante tutto il periodo di locazione.',
        RENTAL_TERMS_22_TITLE: 'Art. 22 - Deposito dell\'autovettura',
        RENTAL_TERMS_22_DESC: 'Qualora il Locatario, durante il periodo di locazione del natante, parcheggiasse la propria autovettura nei pressi del Posteggio Nautico di Guarino Sebastiano e Enzo sito ad Avola in via Sebastiano Morale sn, né lo stesso, né il Locatore avranno obbligo di custodia, pertanto non risponderanno di eventuali furti totali o parziali, incendio e/o altri danni altri sulla autovettura.',
        RENTAL_TERMS_23_TITLE: 'Art. 23 - Foro esclusivo',
        RENTAL_TERMS_23_DESC: 'Per ogni controversia nascente o comunque derivante dal presente contratto sarà territorialmente competente il Foro di Siracusa competente per valore e per materia secondo la legge.',
        RENTAL_TERMS_24_TITLE: 'Art. 24 - Tutela della privacy',
        RENTAL_TERMS_24_DESC: 'Con riferimento alle disposizioni previste dal D. Lgs. 30/06/2003 nr. 196 sulla tutela della privacy, le parti si danno atto reciprocamente che i dati personali, forniti obbligatoriamente per la stipula del presente Contratto di Locazione e Condizioni di Locazione, sono oggetto di trattamento informatico e/o manuale e potranno essere utilizzati esclusivamente per gli adempimenti degli obblighi contrattuali, la gestione amministrativa del rapporto locativo, rapporti con l\'autorità giudiziaria e per adempimenti di legge relativi a norme civilistiche, fiscali e contabili.',
        RENTAL_TERMS_FOOTER: 'Ai sensi degli artt. 1341 e 1342 C.C. il conduttore dichiara espressamente di aver letto, compreso ed approvato gli Art. 3 (Assicurazione), 4 (Abilitazione alla conduzione dell’unità), 5 (Consegna e riconsegna), 6 (Rischio di trasferimento del natante), 7 (Ritardi), 9 (Condizioni del natante), 10 (Danni e perdite dotazioni), 14 (Uso del natante), 15 (Responsabilità penale e civile), 16 (Danni al natante e da navigazione), 17 (Addebiti per spese sopravvenute e danni occulti), 18 (Danni al locatario ed a terzi), 19 (Impossibilità nell\'uso del natante), 20 (Condizioni meteo avverse), 23 (Foro esclusivo), e per accettazione le sottoscrive.'
    }
};