module.exports = {
    it: {
        LEASE_CONTRACT: 'Contratto di Locazione',
        DATE: 'Data',
        REGISTRY_NO: 'Nr. Registro',
        LEASEHOLDER_DETAILS: 'Anagrafica Locatore',
        BOAT_DETAILS: 'Dati Natante Locato',
        BOAT_TYPE: 'Natante',
        VIN: 'Matricola',
        ENGINE: 'Motore',
        REG_NO: 'Targa',
        TANK: 'Serbatoio',
        CUSTOMER_DETAILS: 'Anagrafica Locatario/Conduttore',
        CUSTOMER_NAME: 'Locatario',
        BIRTH_PLACE: 'Luogo di nascita',
        BIRTH_DATE: 'Data di nascita',
        HOME_TOWN: 'Citta di residenza',
        HOME_ADDRESS: 'Indirizzo',
        SSN: 'Codice Fiscale',
        BOAT_LICENSE: 'Patente nautica',
        NONE: 'Nessuna',
        PHONE: 'Telefono',
        EMAIL: 'Email',
        ID_TYPE: 'Tipo documento',
        ID_NUMBER: 'Nr. documento',
        ISSUED_BY: 'Rilasciato da',
        ISSUE_DATE: 'Data rilascio',
        LEASE_DETAILS: 'Dettagli locazione',
        START_DATE: 'Data inizio',
        END_DATE: 'Data fine',
        START_TIME: 'Ora inizio',
        END_TIME: 'Ora fine',
        START_FUEL: 'Carburante inizio',
        END_FUEL: 'Carburante fine',
        FUEL_COST: 'Costo carburante',
        FUEL_TOTAL: 'Totale carburante',
        RENT_PRICE: 'Importo locazione',
        SECURITY_DEPOSIT: 'Cauzione',
        DEPOSIT: 'Importo in acconto',
        BALANCE: 'Importo a saldo'
    }
};